version: '3.7'

networks:
#This isnt needed unless you need multiple containers to talk to each other
  docker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 12.12.0.0/16

services:
  postgres-usage-db:
  #alpine versions of images tend to be more secure.
      image: postgres:12.4-alpine
      restart: always
      container_name: postgres-alpine
      hostname: postgres
      environment:
        POSTGRES_PASSWORD: '!QAZ2wsx'
        POSTGRES_DB: classtime
        POSTGRES_USER: ian
        PGDATA: '/var/pg'
      expose: 
        - '8080'
        - '5432'
      ports:
        - "8080:8080"
        - "5432:5432"
      volumes:
        - C:\Users\ian.rubenstein\repos\dockerCollection\postgres\data:/var/pg:cached
        - C:\Users\ian.rubenstein\repos\dockerCollection\sample_data:/app/data_import/:cached
      networks:
        - docker-network
      security_opt:
        - seccomp:unconfined
